luxteam/rpr_pipelines

- vars/getBranchTag.groovy
- vars/multiplatform_pipeline.groovy
- vars/rbs_push_job_status.groovy
- vars/rbs_set_tester.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
- Fixed requests for setting testers
- Fixed request for end build with ended time
> Sending into RBS

- vars/radeonpro_imageprocessing_pipeline.groovy
Rename files changed in project repo
> Fix for RadeonProImageProcessing pipeline

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
> Pass param

- vars/radeon_rays_sdk_pipeline.groovy
- vars/radeonpro_imageprocessing_pipeline.groovy
- vars/rpr_baikal_cmake_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
OSX WX9100 has replaced by RXVEGA
Removed Ubuntu WX7100
> STVCIS-597 Fix eGPU name for Mac mini Goto

- vars/rpr_blender28plugin_pipeline.groovy
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/blender_passParams/4/Test_20Report/
> Pass params for blender

- vars/radeonpro_imageprocessing_pipeline.groovy
> Stvcis 698

- vars/rpr_hybrid_pipeline.groovy
Support Debug build for Windows in Hybrid manual job
> Added Release/Debug config processing

- vars/radeon_ml_miopen_pipeline.groovy
- vars/radeon_ml_mps_pipeline.groovy
- vars/radeon_ml_tf_cpu_pipeline.groovy
- vars/radeon_ml_tf_cuda_pipeline.groovy
Add tar archives for *nix to fix symlink issue
> Stvcis 852

- vars/rpr_maxplugin_pipeline.groovy
Because of optimization, default values changed long time ago.
> Changed default parameters values in Max plugin

- vars/multiplatform_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
STVCIS-885 update retry function:
* retry counts now is constant = 2
* retry will catch FlowInterruptedException & RequestAbortedException
* extend debug info
> STVCIS-885 update retry function:

- vars/rpr_core_pipeline.groovy
> path hotfix

- vars/radeonpro_imageprocessing_pipeline.groovy
Tested here https://rpr.cis.luxoft.com/job/RadeonProImageProcessingManual/523/
> Update command line arguments for unittest application

- vars/radeonpro_imageprocessing_pipeline.groovy
1. Rework building, deploying and testing procedures
2. Implement command line key to pass models dir to unit test application
Tested here https://rpr.cis.luxoft.com/view/OpenCL/job/RadeonProImageProcessingManual/551/
> RIF pipeline updates

- vars/checkOutBranchOrScm.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
Reverts luxteam/rpr_pipelines#147
> Revert "Scm update"

- vars/multiplatform_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-997
* TECHNICAL STEPS
* Run manual from https://rpr.cis.luxoft.com/job/maya_engine_version/
* REPORTS
* https://rpr.cis.luxoft.com/job/maya_engine_version/4/
> Add choose of tahoe version

- vars/radeonpro_imageprocessing_pipeline.groovy
Tested here https://rpr.cis.luxoft.com/view/OpenCL/job/RadeonProImageProcessingManual/566/
> RIF: Fix xcopy flags

- vars/rpr_ludashihybrid_pipeline.groovy
Pipeline implementation for Ludahi-Hybrid
> Ludashi-Hybrid [STVCIS-1020]

- vars/radeon_ml_miopen_pipeline.groovy
- vars/radeon_ml_mps_pipeline.groovy
- vars/radeon_ml_pipeline.groovy
- vars/radeon_ml_tf_cpu_pipeline.groovy
- vars/radeon_ml_tf_cuda_pipeline.groovy
Fix incorrect "SUCCESS" build status
> Build status fix

- vars/multiplatform_pipeline.groovy
JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1164
PURPOSE
Fix catch error
EFFECT OF CHANGE
Fixed
TECHNICAL STEPS
- Remove AbortException catch
> Remove cathing abort exception from multiplatform pipeline

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
Changed git log format to avoid EOF error during report building with retry_info
> Fix #169 STVCIS-1033

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1176
* https://adc.luxoft.com/jira/browse/STVCIS-1179
* RELATED PR'S
* https://github.com/luxteam/jobs_launcher/pull/52
* REPORTS
* https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3254
> Fix build reports bug

- vars/rpr_mayaplugin_pipeline.groovy
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1129
* PURPOSE
* Don't throw error when group was skipped
> Fix skipped group error

- vars/rpr_viewer_pipeline.groovy
* JIRA TICKET:
* https://adc.luxoft.com/jira/browse/STVCIS-1011
* PURPOSE
* Add total count support for RPR VIewer.
* PRs IN OTHER REPOSITORIES:
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/58
* REPORTS
* All tests failed: https://rpr.cis.luxoft.com/job/RadeonProViewerManual/669/Test_20Report/
* Full run with some failed tests: https://rpr.cis.luxoft.com/job/RadeonProViewerManual/670/Test_20Report/
* Full: https://rpr.cis.luxoft.com/job/RadeonProViewerManual/676/Test_20Report/
> Total count for Viewer

- vars/rpr_inventorplugin_pipeline.groovy
* JIRA TICKET:
* https://adc.luxoft.com/jira/browse/STVCIS-1110
* PURPOSE
* Create pipeline for Inventor plugin.
* EFFECT OF CHANGE
* Add pipeline for Inventor plugin which include implemented PreBuild and Build stages.
> Inventor plugin pipeline

- vars/render_service_scene_configuration.groovy
* JIRA TICKET:
* https://adc.luxoft.com/jira/browse/STVCIS-1102
* PURPOSE
* Add possibility to read and write some options of Blender scenes from Render Service side.
* EFFECT OF CHANGE
* Add pipeline for read configuration of Blender scene or write new values for options of Blender scene
* PRs IN OTHER REPOSITORIES:
* render_service: https://gitlab.cts.luxoft.com/services/render_service/-/merge_requests/49
* render_service_scripts: https://github.com/luxteam/render_service_scripts/pull/18
* NOTES FOR REVIEWERS
* You can see Render Service instance with this changes here: http://172.26.157.251:81
> [Render Service] Add scene scanning (Blender)

- vars/convertPlatforms.groovy
- vars/multiplatform_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
* None
* Fix fails if no platform selected. Fix exception printing
* Check that parsing platform isn't empty in convertPlatforms function.
* Replace options.sendToUMS by sendToUMS (in call function options is undefined).
*  Maya: https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/3418/
> Fix convertPlatforms function if no platform selected

- vars/rpr_blender28plugin_pipeline.groovy
https://adc.luxoft.com/jira/browse/STVCIS-1267
A solution to RPR_Nodes group timeout issue
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2110/Test_20Report/
> Timeout increased for RPR_nodes

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1282
* PURPOSE
* Archiving report building log
* REPORTS
* https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2073/
> Archiving report building log

- vars/multiplatform_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1304
* Change date time format for retry info
* https://github.com/luxteam/jobs_launcher/pull/62
> change date time format for retry info

- vars/multiplatform_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1223
* Add possibility to run manual jobs on custom nodes
* https://rpr.cis.luxoft.com/job/Dev_maya_custom_tag/9/
> Add custom tester tag

- vars/render_service_convert_job.groovy
- vars/render_service_install_plugin.groovy
- vars/render_service_render_job.groovy
- vars/render_service_scene_configuration.groovy
- https://adc.luxoft.com/jira/browse/STVCIS-1216
- Add possibility for admin to set default plugin on plugin storage page for each tool.
- Move plugin downloading and plugin installation logic to separate function.
- Add plugin downloading and installation step for cenversion and scene scanning RS pipeline
- This PR contains commits from that PR: https://github.com/luxteam/rpr_pipelines/pull/202
- render_service: https://gitlab.cts.luxoft.com/services/render_service/-/merge_requests/51
> [Render Service] Add possibility to set default plugin for each tool 

- vars/render_service_clear_scenes.groovy
- vars/render_service_convert_job.groovy
- vars/render_service_install_plugin.groovy
- vars/render_service_render_job.groovy
- vars/render_service_scene_configuration.groovy
- vars/render_service_viewer_job.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1217
* Check on machine that scenes and plugins was updated or not via sha1 hashes
* All RS pipelines receive hashes of scenes and plugins for check that scenes and plugins was updated or not.
* Implement script for delete old scene or excess of scenes in Render Service Storage (with same logic as for clean plugins' binaries)
* This PR contains commits from that PR: https://github.com/luxteam/rpr_pipelines/pull/207
* render_service: https://gitlab.cts.luxoft.com/services/render_service/-/merge_requests/52
> [Render Service] Check on machine that scene was updated or not

- vars/render_service_scene_configuration.groovy
* JIRA TICKET:
* https://adc.luxoft.com/jira/browse/STVCIS-1102
* PURPOSE
* Implement scene scanning API for Blender scenes for configure desired options from config file (without changes in DB schema and render service scripts)
* EFFECT OF CHANGE
* Add usage of necessary options in scene configuration pipeline.
* RELATED PRs:
* render_service: https://gitlab.cts.luxoft.com/services/render_service/-/merge_requests/53
* render_service_scripts: https://github.com/luxteam/render_service_scripts/pull/19
> [Render Service] Create scene scanning API (Blender)

- vars/unstashCrashInfo.groovy
nodeRetry defined in plugin pipelines 'def nodeRetry = []'
> Add nodeRetryList type

- vars/radeonpro_imageprocessing_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1149
* Add possibility to run performance tests and build report for them.
* Add case for run performance report.
* Stash necessary results of performance tests execution and build report based on them
* https://rpr.cis.luxoft.com/job/RadeonProImageProcessingPerformanceManual/34/Test_20Report/
> RIF performance test

- vars/rpr_blender28plugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1410
* Fix Blender in master
* Fix invalid condition on Blender plugin installation stage
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2307/
> Fix Blender in master

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
https://adc.luxoft.com/jira/browse/STVCIS-1392
Delete hash from binaries name (builds msi/dmg/run)
> Fix binaries name

- vars/ProblemMessageManager.groovy
* none
* Fix general error messages saving
* Fix incorrect logic of general error messages saving
* Common build: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2586/
* Build with general error message: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2587/
* Build with specific error message: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2589/
> Fix general error messages saving

- vars/rpr_matlib_pipeline.groovy
https://adc.luxoft.com/jira/browse/STVCIS-1440
Implement MatLib building 
☣️ Build installers haven't been tested. 
[Manual Job](https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMaterialLibrary/)
> [STVCIS-1440] Implement MaterialLibrary build

- vars/run_with_retries.groovy
* None
* Fix mistake in status check of deploy stage
> Fix mistake in status check of deploy stage

- vars/GithubNotificator.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1513
* Remove condition that prevent updating of error status checks
> Remove condition that prevent updating of error status checks

- vars/ProblemMessageManager.groovy
* None
* Fix function for clear failure messages
* Fix access to map with failure messages in case of clearing messages for specific OS.
* Fail first try: https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/3705/
> Fix function for clear failure messages

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* None
* Fix master
* Fix parsing of mergeablePR param.
* Fix syntax in core and viewer pipelines
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2718/
* Maya: https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/3726/
* Max: https://rpr.cis.luxoft.com/job/RadeonProRenderMaxPluginManual/1035/
* Core: https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/736/
* Viewer: https://rpr.cis.luxoft.com/job/RadeonProViewerManual/781/
> Fix master

- vars/radeonpro_radeonrays_pipeline.groovy
[STVCIS-1548](https://adc.luxoft.com/jira/browse/STVCIS-1548)
`NATIVE` backend has been added to rays repo - need to add test executors calls
https://rpr.cis.luxoft.com/job/RadeonRays_Auto/view/change-requests/job/PR-27/14/
> native engine added

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1465
* Fix multiple engines for packages
* Create necessary sets of tests for runs with packages and multiple engines
* https://rpr.cis.luxoft.com/job/DevPackageRadeonProRenderBlender2.8PluginManual/5/
> Fix multiple engines for packages

- vars/clearBinariesUnix.groovy
* None
* Small fixes for run autotests on Mac with Catalina
* Add mindepth key in clearBinariesUnix script
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2758/Test_20Report/
* Maya: https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/3760/Test_20Report/
> Small fixes for run autotests on Mac with Catalina

- vars/multiplatform_pipeline.groovy
- vars/run_with_retries.groovy
* None
* Fix aborting of jobs
* Add new interruption cause of FlowInterruptedException as cause of user interruption (ExceptionCause)
* Add debug message about adding additional retry
> Fix aborting of jobs

- vars/installBlenderAddon.groovy
- vars/installMSI.groovy
- vars/installMSIPlugin.groovy
- vars/installMatlib.groovy
- vars/outputEnvironmentInfo.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
- vars/uninstallMSI.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1624
* Add try number in name of logs for plugins, Core and RPRViewer
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2780/
* Maya: https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/3788/
> Add try number in name of logs for plugins, Core and RPRViewer

- vars/rpr_mayaplugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1636
* Fix total count script for Maya-Northstar
* Prevent escape sequence '\N' in path for Northstar
* https://rpr.cis.luxoft.com/job/DevRadeonProRenderMayaPluginManual/3/
> Fix total count script for Maya-Northstar

- vars/radeon_ml_pipeline.groovy
https://adc.luxoft.com/jira/browse/STVCIS-1506
RML new cases implementation
> Stvcis 1506

- vars/uninstallMSI.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1596
* Fix script for uninstall MSI plugin
* Maya: https://rpr.cis.luxoft.com/job/DevRadeonProRenderMayaPluginManual/9
> Fix script for uninstall MSI plugin

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1575
* Send data to both Production and Dev UMS
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/97
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2850/
* Maya: https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/3844/
* Max: https://rpr.cis.luxoft.com/job/RadeonProRenderMaxPluginManual/1053/
* Core: https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/762/
* Viewer: https://rpr.cis.luxoft.com/job/RadeonProViewerManual/876/
> Connect dev UMS to pipelines

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1709
* Change test timeouts for regression
> Change test timeouts for regression

- vars/GithubNotificator.groovy
- vars/multiplatform_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1603
* Handle skipped groups
* Check groups which is fully skipped and do not take nodes for them
* Tests can be launched by choosing 'inemankov/handle_skipped_groups' as a branch of pipelines repository and 'inemankov/handle_skipped_groups' as a branch of tests repository
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/96
* jobs_test_blender: https://github.com/luxteam/jobs_test_blender/pull/142
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/199
* jobs_test_max: https://github.com/luxteam/jobs_test_max/pull/49
* jobs_test_core: https://github.com/luxteam/jobs_test_core/pull/30
* jobs_test_rprviewer: https://github.com/luxteam/jobs_test_rprviewer/pull/51
* Blender (Updated 10.13.20 16:16): …
> Handle skipped groups 

- vars/radeonpro_imageprocessing_pipeline.groovy
> Add key for cmake. Enable performance measure

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1710
* Send groups to UMS in case of reading tests from test package
* https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/502/
> Send groups to UMS in case of reading tests from test package

- vars/rpr_hybrid_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1710
* Fix building of list of test stages if no quality was selected
* https://rpr.cis.luxoft.com/job/RadeonProRender-HybridManual/529/
* https://rpr.cis.luxoft.com/job/RadeonProRender-HybridManual/530/
> Fix building of list of test stages if no quality was selected

- vars/radeon_ml_performance_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1740
* Add ML performance tests
* Add pipeline for ML performance tests
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/127
* jobs_test_core: https://github.com/luxteam/jobs_test_core/pull/43
* https://rpr.cis.luxoft.com/job/RadeonMLPerformanceManual/25/
> Add ML performance tests

- vars/rpr_core_internal_pipeline.groovy
- vars/utils.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1721
* Implement building of reports for failed unit tests of Core
* Build report for failed unit tests of Core
* Build summary report for all reports with fails
* HTMLReportsShared: https://github.com/luxteam/HTMLReportsShared/pull/6
* https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/70/
> Reports for failed unit tests of Core

- vars/rpr_core_pipeline.groovy
* None
* Delete Ubuntu 2070 from testers of Core Auto
> Delete Ubuntu 2070 from testers of Core Auto

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_internal_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* None
* Mark status checks as failed if there are failed test cases
> Mark status checks as failed if there are failed test cases

- vars/amfdev_amf_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1981
* Update configuration of AMF autojob
* Build was run on fork of AMF repository from luxteam
* https://rpr.cis.luxoft.com/job/DevGPUOpen-AMF-Auto/job/master/3/
> Update configuration of AMF autojob

- vars/amfdev_amf_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1981
* Set only release configuration in AMF autojob
* Build was run on fork of AMF repository from luxteam
* https://rpr.cis.luxoft.com/job/DevGPUOpen-AMF-Auto/job/master/5/
> Set only release configuration in AMF autojob

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_usdviewer_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2001
* Implement possibility to update baselines for fully skipped groups
* Ignore skipped groups if updating of baselines is detected
* Default behavior: https://rpr.cis.luxoft.com/job/DevRadeonProRenderMayaPluginManual/102/
* Update baselines: https://rpr.cis.luxoft.com/job/DevRadeonProRenderMayaPluginManual/103/
* Build after updating of baselines: https://rpr.cis.luxoft.com/job/DevRadeonProRenderMayaPluginManual/105/
> Implement possibility to update baselines for fully skipped groups

- vars/multiplatform_pipeline.groovy
- vars/radeon_ml_performance_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_internal_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_usdplugin_pipeline.groovy
- vars/rpr_usdviewer_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2034
* Add column with build name
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/151
* Blender (without special name): https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3334/Test_20Report/
* Blender (with some name): https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3333/Test_20Report/
> Add column with build name

- vars/radeon_ml_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1713
* Deploy RML binaries in the end of build stage to gitlab repo
* https://rpr.cis.luxoft.com/job/RadeonML_Manual/136/
> Deploy RML binaries in the end of build stage to gitlab repo

- vars/withNotifications.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2039
* Fix withNotifications search condition
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3520/
> Fix withNotifications search condition

- vars/UniverseClient.groovy
- vars/UniverseClient_tests.groovy
https://adc.luxoft.com/jira/browse/STVCIS-1820
Send Jenkins URL to UMS and UMS links to jenkins
https://rpr.cis.luxoft.com/job/UMSRadeonProViewerManual/21/
> Attach UMS/Jenkins links

- vars/downloadAssets.groovy
- vars/radeonpro_gamertfx_pipeline.groovy
- vars/receiveFiles.groovy
- vars/rpr_core_internal_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_creoplugin_pipeline.groovy
- vars/sendFiles.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1710
* Pass REMOTE_HOST as a param for scripts for cis_tools
* **THIS PR SHOULD BE MERGED ONLY AFTER MOVING OF BUILDS SERVICE**
* cis_tools: https://github.com/luxteam/cis_tools/pull/10
* https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/865/
> Pass REMOTE_HOST as a param for scripts for cis_tools

- vars/gpuopen_tan_luxoft_pipeline.groovy
- vars/gpuopen_tan_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2070
* Move TAN assets to Gitlab
* https://rpr.cis.luxoft.com/job/DevJobs/job/DevGPUOpen-TAN-Luxoft-Manual/1/
* https://rpr.cis.luxoft.com/job/DevJobs/job/DevGPUOpen-TAN-AMD-Manual/1/
> Move TAN assets to Gitlab

- vars/rpr_blender28plugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2070
* Fix preBuilt plugin in blender pipeline
> Fix preBuilt plugin in blender pipeline

- src/GithubApiProvider.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-1830
* Reduce duration of JWT expiration
* https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginAuto/job/master/3/
> Reduce duration of JWT expiration

- vars/blender_usdhydra_plugin_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_core_internal_pipeline.groovy
- vars/rpr_core_pipeline.groovy
- vars/rpr_maxplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/rpr_usdplugin_pipeline.groovy
- vars/rpr_usdviewer_pipeline.groovy
- vars/rpr_viewer_pipeline.groovy
* None
* Fix core pipelines
* Fix projectRepo in core pipelines
* Call initChecks if githubNotificator exists
> Fix core pipelines

- vars/clearBinariesWin.groovy
> Fix clear binaries win function (#475)

- vars/clearBinariesWin.groovy
- vars/downloadPlugin.groovy
> Fix prebuild

- vars/utils.groovy
- Fix bug with uncorrect return type on Unix nodes
> fix bug with return type

- src/universe/UniverseManager.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2126
* Add missing context variable
> Add missing context variable

- vars/rpr_mayaplugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2126
* Update Maya regression timeout
> Update Maya regression timeout

- vars/uninstallMSI.groovy
* None
* Escape spaces in uninstallMSI function
* https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4549/
> Escape spaces in uninstallMSI function

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2150
* Increase timeouts of deploy stage for Blender and Maya
> Increase timeouts of deploy stage for Blender and Maya

- vars/radeon_rays_sdk_pipeline.groovy
- vars/radeonpro_gltf_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2142
* Remove Ubuntu from RaysSDK and GLTF pipeliens
> Remove Ubuntu from RaysSDK and GLTF pipeliens

- vars/rpr_usdviewer_pipeline.groovy
* None
* Increase get tool timeout in USDViewer pipeline
* https://rpr.cis.luxoft.com/job/RadeonProUSDViewerAuto/job/master/74/
> Increase get tool timeout in USDViewer pipeline

- vars/rpr_usdviewer_pipeline.groovy
* None
* Remove usdviewer autotest
> Remove usdviewer autotest

- vars/rpr_usdviewer_pipeline.groovy
* None
* Update usdviewer Windows building
> Update usdviewer Windows building

- vars/docker_logs_pipeline.groovy
Make logs loading easier
Add ability to get logs from docker container without connecting to machine and copy files
- https://rpr.cis.luxoft.com/job/UMS/job/UMSGetTestingLogs/9/
> Get docker containers logs pipeline

- vars/rpr_usdviewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2197
* Add new key for build RPRViewer
* https://rpr.cis.luxoft.com/job/RadeonProUSDViewerAuto/view/change-requests/job/PR-191/7/
> Add new key for build RPRViewer

- src/universe/UniverseClient.groovy
- vars/rpr_usdviewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2196
* Small fixes for USD Viewer pipeline
* Update timeouts
* Make dirt install more stable (install "baseline" plugin without uninstalling the previous plugin)
* Remove double slash from links to built RPRViewer
* Create badge with a link to UMS only if request to create build was successful
* https://rpr.cis.luxoft.com/job/RadeonProUSDViewerManual/387/
> Small fixes for USD Viewer pipeline

- vars/rpr_usdviewer_pipeline.groovy
* None
* Add 2080TI to autotests of RPRViewer
* https://rpr.cis.luxoft.com/job/RadeonProUSDViewerManual/422/
> Add 2080TI to autotests of RPRViewer

- vars/rpr_usdviewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2220
* Use build scripts from RPRViewer repo
* Use build scripts from RPRViewer repo instead of copying them
* This PR should be merged only after merge of related PR in RPRViewer repo
* OSX building doesn't work now
* RPRViewer: https://github.com/Radeon-Pro/RPRViewer/pull/201
* https://rpr.cis.luxoft.com/job/RadeonProUSDViewerManual/403/
> Use build scripts from RPRViewer repo

- vars/rpr_usdviewer_pipeline.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2267
* Update Windows build stage in RPRViewer pipeline
* MERGE IT ONLY WITH 212 PR IN RPRVIEWER REPO
* https://rpr.cis.luxoft.com/job/RadeonProUSDViewerAuto/view/change-requests/job/PR-212/4/
> Update Windows build stage in RPRViewer pipeline

- src/GithubApiProvider.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2286
* Add retries for github requests
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginAuto/view/change-requests/job/PR-261/15/
> Add retries for github requests

- src/NotificationConfiguration.groovy
- vars/multiplatform_pipeline.groovy
- vars/rpr_usdviewer_pipeline.groovy
- vars/utils.groovy
- vars/withNotifications.groovy
* https://adc.luxoft.com/jira/browse/STVCIS-2251
* Add reboot feature for withNotifications block
* Add possibility to set reboot configuration for withNotifications block
* Add required reboot configuration for current pipelines
* Reboot Windows builder by withNotifications block conf (RPRViewer): https://rpr.cis.luxoft.com/job/RadeonProUSDViewerManual/437/
> Add reboot feature for withNotifications block

- vars/multiplatform_pipeline.groovy
https://rpr.cis.luxoft.com/job/RadeonProImageProcessing/view/tags/job/1.7.1/5/
> Make deploy of RIF and RML on ReportBuilders

- vars/rpr_hybrid_pipeline.groovy
* None
* Do not create branch in HybridVsNortstar repo for Hybrid branches
* https://rpr.cis.luxoft.com/job/RadeonProRender-Hybrid/job/update-rpr-api/4/
> Do not create branch in HybridVsNortstar repo for Hybrid branches

- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
Reverts luxteam/rpr_pipelines#644
> Revert "Remove NVidia from Blender & Maya autotests"

- vars/rpr_mayaplugin_pipeline.groovy
* None
* Close Maya before tests on Apple M1
* https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/5013/
> Close Maya before tests on Apple M1

- vars/amfdev_streaming_sdk_pipeline.groovy
https://rpr.cis.luxoft.com/job/DevJobs/job/DevStreamingSDKManual/489/
> Deploy reports to NAS (Streaming SDK)

- vars/amfdev_streaming_sdk_pipeline.groovy
- vars/utils.groovy
https://rpr.cis.luxoft.com/job/DevJobs/job/DevStreamingSDKManual/509/
> Reboot nodes before test (Streaming SDK)

- vars/blender_usdhydra_plugin_pipeline.groovy
- vars/makeArchiveArtifacts.groovy
- vars/radeonpro_imageprocessing_pipeline.groovy
- vars/rpr_blender28plugin_pipeline.groovy
- vars/rpr_usdplugin_pipeline.groovy
* None
* Hotfix for Ubuntu slow archiving of artifacts
* Store large Ubuntu artifacts on NAS
* Store RIF, Houdini and Blender Hydra USD reports on NAS
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/5012/
* Houdini: https://rpr.cis.luxoft.com/job/RadeonProRenderUSDPluginManual/677/
* Blender Hydra: https://rpr.cis.luxoft.com/job/BlenderUSDHydraPluginManual/183/
* RIF: https://rpr.cis.luxoft.com/job/RadeonProImageProcessingManual/1010/
> Hotfix for Ubuntu slow archiving of artifacts

- src/NotificationConfiguration.groovy
- vars/rpr_mayaplugin_pipeline.groovy
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/5046/
> Detect corrupted json files

- vars/rpr_hybrid_pipeline.groovy
https://rpr.cis.luxoft.com/job/RadeonProRender-HybridManual/798/
> Fix Hybrid perf tests

- vars/rpr_hybrid_pipeline.groovy
https://rpr.cis.luxoft.com/job/RadeonProRender-HybridManual/800/
> Fix Hybrid updating baselines

- vars/blender_usdhydra_plugin_pipeline.groovy
Use default max samples and threshold to reduce render time
https://github.com/luxteam/jobs_test_usdblender/pull/6
https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/20/
https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/21/
https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/22/
> USDHydra sampling params

- vars/installBlenderAddon.groovy
Correct username instead of null when checking blender plugin existense or uninstalling
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/5166/
> Fix null username on OSX

- src/universe/UniverseManagerDefault.groovy
- src/universe/UniverseManagerEngine.groovy
- src/universe/UniverseManagerFactory.groovy
- https://luxproject.luxoft.com/jira/browse/STVCIS-2518
- Fix error: update_baseline flag doesn't work for UMS
- Update baseline for ums works as aspecte (changed type of value before send; parent build upd_baseline flag now sync with child)
- https://ums.cistest.luxoft.com/products/5f3b1557929d5171e9d25757/611852121b628b8d23546bae/summary
- https://ums.cistest.luxoft.com/products/5f3b1557929d5171e9d25757/61184be11b628b8d23546b5d/summary
> STVCIS-2518/fix updRefs

- vars/blender_usdhydra_plugin_pipeline.groovy
https://rpr.cis.luxoft.com/job/BlenderUSDHydraPluginAuto/job/master/79/
> Fix Blender USD Hydra autotests (download plugin each time; do not use PluginBinaries)

- vars/radeon_ml_pipeline.groovy
> removed TF param

- vars/radeon_ml_pipeline.groovy
- vars/radeonpro_imageprocessing_pipeline.groovy
* https://luxproject.luxoft.com/jira/browse/STVCIS-2531
* Run ML FT on Apple architecture
* Split run_tests.py script to call tool with Apple architecture and process results with Intel python
* Run build and test stages with MacOS_ARM in auto job
* https://rpr.cis.luxoft.com/job/RadeonML_Manual/277/
> Run ML FT on Apple architecture

- src/GithubApiProvider.groovy
Reverts luxteam/rpr_pipelines#744
> Revert "Retry any failed request (GithubNotificator)"

- vars/rpr_blenderplugin_pipeline.groovy
- vars/rpr_mayaplugin_pipeline.groovy
- vars/utils.groovy
* https://luxproject.luxoft.com/jira/browse/STVCIS-2543
* Add a feature for core performance drop catch
* Add "render time history" char in performance tab
* Analyze performance drop catch (> 5% difference -> message in base table)
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/220
* jobs_test_blender: https://github.com/luxteam/jobs_test_blender/pull/277
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/369
* Blender: https://rpr.cis.luxoft.com/job/DevJobs/job/DevRadeonProRenderBlender2.8PluginManual/112/
> Add a feature for core performance drop catch

- vars/amfdev_streaming_sdk_pipeline.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-2502
- Add new games CS:GO and Dota 2
- https://rpr.cis.luxoft.com/job/DevJobs/job/DevStreamingSDKManual/777/ -  Dota 2 general & generalQoS
- https://rpr.cis.luxoft.com/job/DevJobs/job/DevStreamingSDKManual/780/ - Dota 2 general Android
- https://github.com/luxteam/jobs_test_streaming_sdk/pull/61
> New games kill process

- vars/rpr_mayausd_pipeline.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-2738
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaUSDPluginManual/13/
> MayaUSD build

- vars/rpr_hybrid_pipeline.groovy
> Disabled Ubuntu 18 in autojobs

- vars/amdDriverUpdate.groovy
https://rpr.cis.luxoft.com/job/Utils/job/AMD_driver_update/16/
> AMD driver update cleanWS before execution

- vars/radeon_ml_upscalers_pytorch.groovy
Remove building of docker
Speeds up testing for upscaler pipeline
> Removed building docker for upscalers

- vars/gpuopen_tan_luxoft_pipeline.groovy
- vars/gpuopen_tan_pipeline.groovy
-
Сustomer review.
Restored RoomAcousticsQT build and deploy.
> Tan amf load testing

- vars/radeon_ml_upscalers_pytorch.groovy
Increase timeout value
Increase timeout value
> Increase timeout value

- vars/radeon_ml_upscalers_pytorch.groovy
Reverts luxteam/rpr_pipelines#908
> Revert "Disable option abortOldAutoBuilds in upscaler pipeline"

- vars/blender_usdhydra_plugin_pipeline.groovy
> Changed VStudio version to 19

- vars/multiplatform_pipeline.groovy
- vars/rpr_mayausd_pipeline.groovy
- vars/rpr_usdviewer_pipeline.groovy
- vars/run_with_retries.groovy
1) Вьювер требует дефолтную вейрсию смейка выше 319 - прописал в path cmake 323 версии;
2) MayaUSD билд не укладывается в 1 час таймаута
https://rpr.cis.luxoft.com/job/RadeonProUSDViewerManual/867/ - Билд Вьювера с симейком
https://rpr.cis.luxoft.com/job/RadeonProRenderBlenderPluginManual/5786/ - Удаление папок перед билдом #1
https://rpr.cis.luxoft.com/job/RadeonProRender-HybridManual/849/ - Удаление папок перед билдом #2
> Changes for cloud builders

- vars/run_with_retries.groovy
> Deleted cleanws function calling

- vars/rpr_core_pipeline.groovy
https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/1337/
> Added hybridPro skips for not rtx cards

- vars/blender_usdhydra_plugin_pipeline.groovy
- vars/rpr_inventorplugin_installer_pipeline.groovy
- vars/rpr_usdviewer_pipeline.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-2844
https://luxproject.luxoft.com/jira/browse/STVCIS-2766
Add performance history to USDHydra and Inventor
https://github.com/luxteam/jobs_test_usdblender/pull/61
https://github.com/luxteam/jobs_test_inventor/pull/168
https://github.com/luxteam/jobs_test_usdviewer/pull/7
https://rpr.cis.luxoft.com/job/BlenderUSDHydraPluginManual/776/
https://rpr.cis.luxoft.com/job/RadeonProRenderInventorPluginInstallerManual/134/
> Added support for perf.history to USDHydra, USDViewer, Inventor

- vars/radeonpro_webusdviewer_pipeline.groovy
- vars/webusd_set_env.groovy
Jira Ticket
https://luxproject.luxoft.com/jira/browse/STVCIS-2909
Purpose
Auto job for WebUSD build&deploy process
⚠️ Notes for Reviewers
:octocat: Related PR'S
Jenkins Builds
> Webusd deploy manual&auto

- vars/rpr_inventorplugin_installer_pipeline.groovy
> Updated cmake version in path

- vars/radeonpro_webusdviewer_pipeline.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3062
Add logic for notifications by Telegram Bot
> Notifications by TG bot & Sanyize checks

- vars/rpr_blenderplugin_pipeline.groovy
- vars/utils.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3129
Created a function that compares the latest Windows AMD GPU driver with the current driver.
https://rpr.cis.luxoft.com/job/RPR-BlenderPlugin-Manual/6114/
> Compare the latest Windows AMD GPU driver with the current driver

- vars/rpr_mayausd_pipeline.groovy
> Add version increment (Maya USD)

- vars/webusdviewer_submodules_pipeline.groovy
> Fix incrementing of Web USD version in main branches

- vars/rpr_hybrid_pipeline.groovy
https://rpr.cis.luxoft.com/job/RadeonProRender-Hybrid/job/PR-1042/12
> Commented string with gpu driver validating

- vars/amdDriverUpdate.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-2810
https://github.com/luxteam/cis_tools/pull/74
https://rpr.cis.luxoft.com/job/Utils/job/AMD_driver_update/156/
> Ubuntu drivers update

- vars/amfdev_streaming_sdk.groovy
Reverts luxteam/rpr_pipelines#1342
> Revert "Temporary remove install_pylibs call"

- vars/hybrid.groovy
Reverts luxteam/rpr_pipelines#1381
> Revert "Incremental build for Hybrid"

- vars/hdrpr.groovy
Reverts luxteam/rpr_pipelines#1443
> Revert "HdRPR - unskip old GPUs"

- vars/render_studio.groovy
Reverts luxteam/rpr_pipelines#1454
> Revert "Check number of observed cases during nofits sending (RS)"

- vars/usd_houdini.groovy
Reverts luxteam/rpr_pipelines#1489
> Revert "Temporary remove 9100 from Houdini autojob"

- vars/render_studio.groovy
Reverts luxteam/rpr_pipelines#1495
> Revert "Update HybridPro using in RS"

- vars/usd_maya.groovy
> Removed depend to PR in windows build

- vars/usd_houdini.groovy
> Use VS 2019 to build Houdini plugin 19.0

- vars/summary.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3666
https://rpr.cis.luxoft.com/job/DevJobs/job/JenkinsSummary/15/
> Implement base of Jenkins summary pipeline

- vars/usd_houdini.groovy
Reverts luxteam/rpr_pipelines#1569
> Revert "Remove 680M for Houdini testing"

- vars/amfdev_streaming_sdk.groovy
> Stabilize StreamingSDK pipeline

- vars/usd_houdini.groovy
> Fix Ubuntu Houdini autotests

- vars/rpr_sdk.groovy
https://rpr.cis.luxoft.com/job/RPR-SDK-Manual/1478/
> Added m2 to rprsdk autotests

- vars/baseline_updater_pipeline.groovy
- vars/hdrpr.groovy
- vars/hybrid_mtlx.groovy
- vars/render_studio.groovy
- vars/rpr_anari.groovy
- vars/rpr_blender.groovy
- vars/rpr_maya.groovy
- vars/rpr_sdk.groovy
- vars/usd_blender.groovy
- vars/usd_houdini.groovy
- vars/usd_inventor_installer.groovy
- vars/usd_maya.groovy
- vars/usd_viewer.groovy
Will be merged after the release
> Save additional info with baselines

- vars/amfdev_streaming_sdk.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3783
False:
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDebug3/23/
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDebug3/22/
True:
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDebug3/21/
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDebug3/20/
> rename streaming traces to streaming dump

- vars/rpr_blender.groovy
- vars/rpr_maya.groovy
- vars/usd_blender.groovy
- vars/usd_houdini.groovy
- vars/usd_maya.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3697
> Add perf history feature for all auto projects

- vars/rpr_blender.groovy
https://rpr.cis.luxoft.com/job/RPR-BlenderPlugin-Manual/6821/
> Fixed path to build logs blender

- vars/vaultwarden_update_passwords.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3802
- Installed `jq` and `bitwarden-cli` on TBILISI
- MacOS is skipped, because password change via anydesk cli doesn't work on it (GUI password change will be implemented in the future)
- Every build requires input with vaultwarden email and password to continue
https://rpr.cis.luxoft.com/job/Utils/job/VaultwardenUpdatePasswords/30
> Vaultwarden pipeline to update passwords

- vars/rpr_blender.groovy
- vars/rpr_maya.groovy
- vars/rpr_sdk.groovy
- vars/usd_houdini.groovy
Reverts luxteam/rpr_pipelines#1682
> Revert "Switch to solution with old NAS"

- vars/increment_version.groovy
- vars/render_studio.groovy
- vars/render_studio_submodules.groovy
- vars/rpr_anari.groovy
- vars/rpr_blender.groovy
- vars/rpr_maya.groovy
- vars/usd_blender.groovy
- vars/usd_houdini.groovy
- vars/usd_inventor_installer.groovy
- vars/usd_maya.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3935
https://rpr.cis.luxoft.com/job/DevJobs/job/VersionIncrement/
> Implement pipeline for plugin version updating

- vars/update_sceneLM.groovy
- vars/update_scene_lm.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-3976
https://rpr.cis.luxoft.com/job/DevJobs/job/UpdateSceneLM/
> Implement script for Live Mode scene syncronization

- vars/render_studio.groovy
> Save summary_results.json for RS builds

- vars/usd_houdini.groovy
https://luxproject.luxoft.com/jira/browse/STVCIS-4068
modifying for auto login into Houdini License Administrator
> add login script running logic

- vars/hybrid_sdk.groovy
- vars/hybrid_unit.groovy
Reverts luxteam/rpr_pipelines#1771
> Revert "Reboot Ubuntu devices"
